spring.datasource.url: jdbc:h2:file:./camunda-h2-database

spring.flyway.url: jdbc:h2:file:./camunda-h2-database

spring.datasource.driverClassName: org.h2.Driver
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

spring.h2.console.enabled: true

spring.flyway.baseline-on-migrate: true
server.port: 8081

camunda.bpm.admin-user:
  id: demo
  password: demo

